frameworkVersion: "3"
service: prisma-serverless-prisma-mongo
useDotenv: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-esbuild
  - serverless-prune-plugin

custom:
  esbuild:
    minify: true
    watch:
      pattern: app/**/*.ts # default .
      # ignore: ['.serverless/**/*', '.build'] # default ['.build', 'dist', 'node_modules']

  prune:
    automatic: true
    includeLayers: true
    number: 1

  environment:
    dev:
      DATABASE_URL: ${env:DATABASE_URL_TEST}
    qa:
      DATABASE_URL: ${env:DATABASE_URL_QA}
    test:
      DATABASE_URL: ${env:DATABASE_URL_TEST}
    prod:
      DATABASE_URL: ${env:DATABASE_URL}

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  runtime: nodejs16.x

  environment:
    DATABASE_URL: ${self:custom.environment.${self:provider.stage}.DATABASE_URL}

functions:
  status:
    handler: app/components/status.
    timeout: 10
    events:
      - httpApi:
          method: GET
          path: /

  seed:
    handler: app/components/seed.handler
    timeout: 10
    events:
      - httpApi:
          method: GET
          path: /api/seed

  getUsers:
    handler: app/components/users.handler
    timeout: 10
    events:
      - httpApi:
          method: GET
          path: /api/users

  createUser:
    handler: app/components/create-user.handler
    timeout: 10
    events:
      - httpApi:
          method: POST
          path: /api/users

# only include the Prisma binary required on AWS Lambda while packaging
package:
  patterns:
    - "!node_modules/.prisma/client/libquery_engine-*"
    - "!node_modules/.prisma/client/*query_engine-windows*"
    - "node_modules/.prisma/client/*query_engine-debian-*"
    - "node_modules/.prisma/client/*query_engine-rhel-*"
    - "node_modules/.prisma/client/schema.prisma"
    - "!node_modules/prisma/libquery_engine-*"
    - "!node_modules/@prisma/engines/**"
