name: Node Lambda Deployment with Github Action

on:
  push:
    branches:
      - 'qa'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: 🐣 Checking out project
        uses: actions/checkout@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: 💻 Install project
        run: npm ci
     
      - name: 🚀 Deploy lambda function
        uses: serverless/github-action@v3.1
        with:
          args: deploy --stage qa
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_URL_QA: ${{ secrets.DATABASE_URL_QA }}
          DATABASE_URL_TEST: ${{ secrets.DATABASE_URL_TEST }}